from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar
from uuid import UUID

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.load_balancer_problem_invalid_param_response import LoadBalancerProblemInvalidParamResponse


T = TypeVar("T", bound="LoadBalancerProblemResponse")


@_attrs_define
class LoadBalancerProblemResponse:
    """Represents an error object following the Problem Details specification (RFC7807). Provides machine-readable and
    human-readable information about an error that occurred while processing a request.

        Example:
            {'type': 'https://api.example.com/problems/invalid-request', 'title': 'Invalid request', 'detail': 'The provided
                domain name is not valid.', 'status': 400, 'invalid_params': [{'name': 'hostnames[0]', 'reason': 'Invalid domain
                name format'}], 'correlation_id': 'req-8b29d3a6a4cf4d22a17e2b8e31cd4a12'}

        Attributes:
            type_ (str): A URI reference identifying the problem type. When dereferenced, it typically provides human-
                readable documentation for the error. Example: https://api.example.com/problems/invalid-request.
            title (str): A short, human-readable summary of the problem type. This value should not vary between occurrences
                of the same error type. Example: Invalid request.
            status (int): The HTTP status code generated by the origin server for this occurrence of the problem. Example:
                400.
            detail (str | Unset): A human-readable explanation specific to this occurrence of the problem. Example: The
                provided domain name is not valid..
            invalid_params (list[LoadBalancerProblemInvalidParamResponse] | Unset): A list of invalid parameters that caused
                the problem. Used to provide detailed feedback for validation errors. Example: [{'name': 'hostnames[0]',
                'reason': 'Invalid domain name format'}].
            correlation_id (UUID | Unset): A unique identifier for this error instance, useful for tracing or debugging
                requests. Example: req-8b29d3a6a4cf4d22a17e2b8e31cd4a12.
    """

    type_: str
    title: str
    status: int
    detail: str | Unset = UNSET
    invalid_params: list[LoadBalancerProblemInvalidParamResponse] | Unset = UNSET
    correlation_id: UUID | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        type_ = self.type_

        title = self.title

        status = self.status

        detail = self.detail

        invalid_params: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.invalid_params, Unset):
            invalid_params = []
            for invalid_params_item_data in self.invalid_params:
                invalid_params_item = invalid_params_item_data.to_dict()
                invalid_params.append(invalid_params_item)

        correlation_id: str | Unset = UNSET
        if not isinstance(self.correlation_id, Unset):
            correlation_id = str(self.correlation_id)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "type": type_,
                "title": title,
                "status": status,
            }
        )
        if detail is not UNSET:
            field_dict["detail"] = detail
        if invalid_params is not UNSET:
            field_dict["invalid_params"] = invalid_params
        if correlation_id is not UNSET:
            field_dict["correlation_id"] = correlation_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.load_balancer_problem_invalid_param_response import (
            LoadBalancerProblemInvalidParamResponse,  # noqa: PLC0415
        )

        d = dict(src_dict)
        type_ = d.pop("type")

        title = d.pop("title")

        status = d.pop("status")

        detail = d.pop("detail", UNSET)

        _invalid_params = d.pop("invalid_params", UNSET)
        invalid_params: list[LoadBalancerProblemInvalidParamResponse] | Unset = UNSET
        if _invalid_params is not UNSET:
            invalid_params = []
            for invalid_params_item_data in _invalid_params:
                invalid_params_item = LoadBalancerProblemInvalidParamResponse.from_dict(invalid_params_item_data)

                invalid_params.append(invalid_params_item)

        _correlation_id = d.pop("correlation_id", UNSET)
        correlation_id: UUID | Unset
        if isinstance(_correlation_id, Unset):
            correlation_id = UNSET
        else:
            correlation_id = UUID(_correlation_id)

        load_balancer_problem_response = cls(
            type_=type_,
            title=title,
            status=status,
            detail=detail,
            invalid_params=invalid_params,
            correlation_id=correlation_id,
        )

        return load_balancer_problem_response
