minimum_pre_commit_version: 2.15.0
ci:
  autofix_prs: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
