[project]
name = "upcloud-python-api-dev"
version = "0.0.0"
requires-python = ">=3.11,<4"
dependencies = ["upcloud-api"]

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
    "tomlkit",
]

[tool.uv]
required-version = ">=0.12.9,<0.13.0"
package = false

[tool.uv.workspace]
members = ["sdk"]

[tool.uv.sources]
upcloud-api = { workspace = true }

[tool.ruff]
target-version = "py311"
exclude = [
    ".git",
    "ENV",
    "__pycache__",
    "build",
    "sdk",
    "generator",
]
line-length = 99

[tool.ruff.lint]
ignore = [
    "D100",
    "D104",
    "D105",
    "D200",
    "D202",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "D403",
    "D415",
    "E501",
]
select = [
    "B",
    "D",
    "E",
    "F",
    "I",
    "S",
    "UP",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"*/__init__.py" = ["F401"]
"test/*" = [
    "D",
    "F841",
    "S101",
    "S105",
    "S106",
    "B011",
]

[tool.ruff.format]
quote-style = "preserve"
