[project]
name = "upcloud-api"
version = "2.9.0"
description = "UpCloud API Client"
readme = "README.md"
requires-python = ">=3.10,<4"
license = "MIT"
license-files = ["LICENSE.txt"]
dependencies = ["requests"]

[[project.maintainers]]
name = "UpCloud"
email = "hello@upcloud.com"

[project.optional-dependencies]
keyring = ["keyring>=23.0"]

[project.urls]
Homepage = "https://github.com/UpCloudLtd/upcloud-python-api"

[dependency-groups]
dev = [
    "keyring",
    "mock",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "responses",
    "ruff",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "upcloud_api"
module-root = ""
source-include = [
    "docs/**",
    "mkdocs.yml",
    "test/conftest.py",
    "test/json_data/**",
    "test/test_*.py",
]

[tool.pytest.ini_options]
addopts = [
    "--cov=test",
    "--cov=upcloud_api",
    "--cov-report=term-missing",
]
testpaths = ["test"]

[tool.black]
line-length = 99
target-version = ["py310"]
skip-string-normalization = true

[tool.ruff]
target-version = "py310"
exclude = [
    ".git",
    "ENV",
    "__pycache__",
    "build",
]
ignore = [
    "D100",
    "D104",
    "D105",
    "D200",
    "D202",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "D403",
    "D415",
    "E501",
]
line-length = 99
select = [
    "B",
    "D",
    "E",
    "F",
    "I",
    "S",
    "UP",
    "W",
]

[tool.ruff.per-file-ignores]
"*/__init__.py" = ["F401"]
"test/*" = [
    "D",
    "F841",
    "S101",
    "S105",
    "S106",
    "B011",
]
