[project]
name = "upcloud-api"
version = "3.0.0.dev0"
description = "A client library for accessing UpCloud API"
authors = []
maintainers = [{ name = "UpCloud", email = "hello@upcloud.com" }]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
dependencies = [
    "httpx>=0.23.1,<0.29.0",
    "attrs>=22.2.0",
]

[project.urls]
Homepage = "https://github.com/UpCloudLtd/upcloud-python-api"

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
    "tomlkit",
]

[tool.uv]
required-version = ">=0.12.9,<0.13.0"

[tool.uv.build-backend]
module-name = "upcloud_api"
module-root = ""

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py311"
exclude = [
    ".git",
    "ENV",
    "__pycache__",
    "build",
    "upcloud_api",
    "generator",
]
line-length = 99

[tool.ruff.lint]
ignore = [
    "D100",
    "D104",
    "D105",
    "D200",
    "D202",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "D403",
    "D415",
    "E501",
]
select = [
    "B",
    "D",
    "E",
    "F",
    "I",
    "S",
    "UP",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"*/__init__.py" = ["F401"]
"test/*" = [
    "D",
    "F841",
    "S101",
    "S105",
    "S106",
    "B011",
]

[tool.ruff.format]
quote-style = "preserve"
