#!/usr/bin/env bash
set -euo pipefail

echo "== Python SDK GENERATION (openapi-python-client) =="

SPEC_PATH="generator/openapi/spec.json"
PATCHED_SPEC_PATH="generator/openapi/spec.patched.json"
OUT_DIR="upcloud_api"
TMP_DIR=".tmp-openapi-python-client"

if [ ! -f "$SPEC_PATH" ]; then
  echo "ERROR: Missing spec file at $SPEC_PATH"
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 not found"
  exit 1
fi

OPENAPI_PYTHON_CLIENT_VERSION="0.29.1"

echo "Cleaning temp/output dirs..."
rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"

echo "TMP_DIR exists before generate? $( [ -d "$TMP_DIR" ] && echo yes || echo no )"
ls -la "$TMP_DIR" 2>/dev/null || true

# TODELETE: Temp fix to remove broken operations from OpenAPI spec
echo "Patching OpenAPI spec: removing known-broken operations..."
python3 generator/scripts/patch_openapi.py "$SPEC_PATH" "$PATCHED_SPEC_PATH"

echo "Generating SDK..."
uvx --from "openapi-python-client==${OPENAPI_PYTHON_CLIENT_VERSION}" openapi-python-client generate \
  --path "$PATCHED_SPEC_PATH" \
  --config generator/config/openapi-python-client.yml \
  --custom-template-path generator/templates \
  --output-path "$TMP_DIR" \
  --meta uv \
  --overwrite

if [ ! -d "$TMP_DIR/upcloud_api" ]; then
  echo "ERROR: Generator did not produce $TMP_DIR/upcloud_api"
  exit 1
fi

echo "Syncing generated package into $OUT_DIR/ ..."
rm -rf "$OUT_DIR"
cp -R "$TMP_DIR/upcloud_api" "$OUT_DIR"

echo "Writing spec version..."
SPEC_VERSION="$(python3 -c "import json; print(json.load(open('$SPEC_PATH'))['info']['version'])")"
cat > "$OUT_DIR/spec_version.py" <<EOF
"""Auto-generated by generator/scripts/generate.sh. Do not edit."""

SPEC_VERSION = "${SPEC_VERSION}"
EOF

echo "Exposing SPEC_VERSION from package __init__..."
python3 - "$OUT_DIR/__init__.py" <<'PYEOF'
import re
import sys

path = sys.argv[1]
content = open(path).read()
content = content.replace(
    "from .client import AuthenticatedClient, Client",
    "from .client import AuthenticatedClient, Client\nfrom .spec_version import SPEC_VERSION",
)
content = re.sub(
    r'__all__ = \(\n(.*?)\n\)',
    lambda m: '__all__ = (\n' + m.group(1) + '\n    "SPEC_VERSION",\n)',
    content,
    flags=re.DOTALL,
)
open(path, "w").write(content)
PYEOF

echo "Generation complete."
