from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.account_tokens_problem_invalid_params_item import AccountTokensProblemInvalidParamsItem


T = TypeVar("T", bound="AccountTokensProblem")


@_attrs_define
class AccountTokensProblem:
    """JSON Problem Details for HTTP APIs

    Attributes:
        type_ (str): A URI reference that uniquely identifies the problem type only in the context of the provided API.
            It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique
            for the problem type.
        title (str): A short summary of the problem type. Written in English and readable for engineers, usually not
            suited for non technical stakeholders and not localized.
        status (int): The HTTP status code generated by the origin server for this occurrence of the problem.
        detail (str | Unset): A human readable explanation specific to this occurrence of the problem that is helpful to
            locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not
            suited for non technical stakeholders and not localized.
        invalid_params (list[AccountTokensProblemInvalidParamsItem] | Unset):
        correlation_id (str | Unset): A unique identifier for the request. This identifier is generated by the server
            and can be used to track the request in the server logs. It is useful for debugging and support purposes.
    """

    type_: str
    title: str
    status: int
    detail: str | Unset = UNSET
    invalid_params: list[AccountTokensProblemInvalidParamsItem] | Unset = UNSET
    correlation_id: str | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        type_ = self.type_

        title = self.title

        status = self.status

        detail = self.detail

        invalid_params: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.invalid_params, Unset):
            invalid_params = []
            for invalid_params_item_data in self.invalid_params:
                invalid_params_item = invalid_params_item_data.to_dict()
                invalid_params.append(invalid_params_item)

        correlation_id = self.correlation_id

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "type": type_,
                "title": title,
                "status": status,
            }
        )
        if detail is not UNSET:
            field_dict["detail"] = detail
        if invalid_params is not UNSET:
            field_dict["invalid_params"] = invalid_params
        if correlation_id is not UNSET:
            field_dict["correlation_id"] = correlation_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account_tokens_problem_invalid_params_item import (
            AccountTokensProblemInvalidParamsItem,  # noqa: PLC0415
        )

        d = dict(src_dict)
        type_ = d.pop("type")

        title = d.pop("title")

        status = d.pop("status")

        detail = d.pop("detail", UNSET)

        _invalid_params = d.pop("invalid_params", UNSET)
        invalid_params: list[AccountTokensProblemInvalidParamsItem] | Unset = UNSET
        if _invalid_params is not UNSET:
            invalid_params = []
            for invalid_params_item_data in _invalid_params:
                invalid_params_item = AccountTokensProblemInvalidParamsItem.from_dict(invalid_params_item_data)

                invalid_params.append(invalid_params_item)

        correlation_id = d.pop("correlation_id", UNSET)

        account_tokens_problem = cls(
            type_=type_,
            title=title,
            status=status,
            detail=detail,
            invalid_params=invalid_params,
            correlation_id=correlation_id,
        )

        return account_tokens_problem
