name: test

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.0
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env:
          - py37
          - py38
          - py39
          - py310
          - pypy3
    steps:
      - uses: actions/checkout@v3
      - name: Fedora Tox with ${{ matrix.tox_env }}
        uses: fedora-python/tox-github-action@v37.0
        with:
          tox_env: ${{ matrix.tox_env }}
      - uses: actions/setup-python@v4
        with:
          cache: pip
          cache-dependency-path: |
            requirements-dev.txt
            setup.py
  deploy:
    name: Build deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: casperdcl/deploy-pypi@v2.3.2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          build: true
          # only upload if a tag is pushed (otherwise just build & check)
          upload: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
