name: test

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements-dev.txt
      - name: Run flake8
        run: flake8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env:
          - py36
          - py37
          - py38
          - py39
          - pypy3
    steps:
      - uses: actions/checkout@v2
      - name: Fedora Tox with ${{ matrix.tox_env }}
        uses: fedora-python/tox-github-action@v0.4
        with:
          tox_env: ${{ matrix.tox_env }}
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

  mendscan:
    env:
      WS_APIKEY: ${{secrets.MEND_POC_APIKEY}}
      WS_USERKEY: ${{secrets.MEND_POC_USERKEY}}
      WS_WSS_URL: https://saas-eu.mend.io/agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Mend Unified Agent Scan
        env:
          WS_PRODUCTNAME: ${{github.event.repository.name}}
          WS_PROJECTNAME: ${{github.event.repository.name}}_${{github.ref_name}}
          WS_GENERATEPROJECTDETAILSJSON: false
          WS_PYTHON_REQUIREMENTSFILEINCLUDES: "*.txt"
          WS_PYTHON_RESOLVESETUPFILES: true
        run: |
          echo Downloading Mend Unified Agent
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
          if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
            echo "Integrity Check Failed"
          else
            echo "Integrity Check Passed"
            echo Starting Unified Agent Scan
            java -jar wss-unified-agent.jar
          fi

  deploy:
    name: Build deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          build: true
          # only upload if a tag is pushed (otherwise just build & check)
          upload: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
